package dao.hb;

// Generated 2014-9-11 15:41:02 by Hibernate Tools 3.4.0.CR1

/**
 * YwSgdxx generated by hbm2java
 */
public class YwSgdxx implements java.io.Serializable {

	private Integer id;
	private Integer xmxh;
	private String yws;
	private String sfzb;
	private String rwbh;
	private String rwmc;
	private String gdzt;
	private String xmfzr;
	private String ghsjr;
	private String zrghs;
	private String sz;
	private String zghs;
	private String yz;

	public YwSgdxx() {
	}

	public YwSgdxx(Integer xmxh, String yws, String sfzb, String rwbh,
			String rwmc, String gdzt, String xmfzr, String ghsjr, String zrghs,
			String sz, String zghs, String yz) {
		this.xmxh = xmxh;
		this.yws = yws;
		this.sfzb = sfzb;
		this.rwbh = rwbh;
		this.rwmc = rwmc;
		this.gdzt = gdzt;
		this.xmfzr = xmfzr;
		this.ghsjr = ghsjr;
		this.zrghs = zrghs;
		this.sz = sz;
		this.zghs = zghs;
		this.yz = yz;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getXmxh() {
		return this.xmxh;
	}

	public void setXmxh(Integer xmxh) {
		this.xmxh = xmxh;
	}

	public String getYws() {
		return this.yws;
	}

	public void setYws(String yws) {
		this.yws = yws;
	}

	public String getSfzb() {
		return this.sfzb;
	}

	public void setSfzb(String sfzb) {
		this.sfzb = sfzb;
	}

	public String getRwbh() {
		return this.rwbh;
	}

	public void setRwbh(String rwbh) {
		this.rwbh = rwbh;
	}

	public String getRwmc() {
		return this.rwmc;
	}

	public void setRwmc(String rwmc) {
		this.rwmc = rwmc;
	}

	public String getGdzt() {
		return this.gdzt;
	}

	public void setGdzt(String gdzt) {
		this.gdzt = gdzt;
	}

	public String getXmfzr() {
		return this.xmfzr;
	}

	public void setXmfzr(String xmfzr) {
		this.xmfzr = xmfzr;
	}

	public String getGhsjr() {
		return this.ghsjr;
	}

	public void setGhsjr(String ghsjr) {
		this.ghsjr = ghsjr;
	}

	public String getZrghs() {
		return this.zrghs;
	}

	public void setZrghs(String zrghs) {
		this.zrghs = zrghs;
	}

	public String getSz() {
		return this.sz;
	}

	public void setSz(String sz) {
		this.sz = sz;
	}

	public String getZghs() {
		return this.zghs;
	}

	public void setZghs(String zghs) {
		this.zghs = zghs;
	}

	public String getYz() {
		return this.yz;
	}

	public void setYz(String yz) {
		this.yz = yz;
	}

}
