package dao.hb;

// Generated 2014-9-11 15:41:02 by Hibernate Tools 3.4.0.CR1

/**
 * YwXmxx generated by hbm2java
 */
public class YwXmxx implements java.io.Serializable {

	private Integer id;
	private String xmbh;
	private String xmmc;
	private String zbs;
	private String xbs;
	private String htlx;
	private String jb;

	public YwXmxx() {
	}

	public YwXmxx(String xmbh, String xmmc, String zbs, String xbs,
			String htlx, String jb) {
		this.xmbh = xmbh;
		this.xmmc = xmmc;
		this.zbs = zbs;
		this.xbs = xbs;
		this.htlx = htlx;
		this.jb = jb;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getXmbh() {
		return this.xmbh;
	}

	public void setXmbh(String xmbh) {
		this.xmbh = xmbh;
	}

	public String getXmmc() {
		return this.xmmc;
	}

	public void setXmmc(String xmmc) {
		this.xmmc = xmmc;
	}

	public String getZbs() {
		return this.zbs;
	}

	public void setZbs(String zbs) {
		this.zbs = zbs;
	}

	public String getXbs() {
		return this.xbs;
	}

	public void setXbs(String xbs) {
		this.xbs = xbs;
	}

	public String getHtlx() {
		return this.htlx;
	}

	public void setHtlx(String htlx) {
		this.htlx = htlx;
	}

	public String getJb() {
		return this.jb;
	}

	public void setJb(String jb) {
		this.jb = jb;
	}

}
